<?php 
include_once '../models/connect.php';
include_once '../models/UtilityFunctions.php';
include_once '../models/sensor.php';
$pdoConnection = connect();
$utilityFunction =  new UtilityFunctions($pdoConnection);
$alarms = $utilityFunction->getAlarms();
$rooms = $utilityFunction ->getRooms();
$sensors = $utilityFunction ->getSensors();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bravo Smart Office</title>
	<script>
		window.location.href="../index.php"
	</script>
</head>
<body>
	<div class="page_title">
		<img src="./image/detector.png" />
		<div class="buttonText2">Room 601</div>
		<div class="buttonText2">Smoke Detector</div>
	</div>
	<button class="button" id="send_alarm" onclick="sendAlarm()">
		<img src="./image/alarm.png" />
		<div class="buttonText1">click here to</div>
		<div class="buttonText2">ALARM!</div>
	</button>
	<div id="table_block">
		<table id="table">
			<tr>
				<td>DATE(DD/MM/YYYY)</td>
				<td>SENSOR ID</td>
				<td>TYPE</td><!--auto generated by monitor data-->
				<td>ROOM</td>
			</tr>
			<?php
				foreach ($alarms as $alarm) {
                    $room = getSensorRoom($alarm['idsensor']);
					echo("
					
						<tr>
							<td> $alarm[time] </td>
							<td>$alarm[idsensor]</td>
							<td>$alarm[type]</td>
							<td>Room $room</td>
						</tr>
					");
				}
			?>
		</table>
	</div>
</body>
</html> 