<?php 
include_once '../models/connect.php';
include_once '../models/UtilityFunctions.php';
$pdoConnection = connect();
$utilityFunction =  new UtilityFunctions($pdoConnection);
$alarms = $utilityFunction->getAlarms();
$rooms = $utilityFunction ->getRooms();
$sensors = $utilityFunction ->getSensors();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bravo Smart Office</title>
	<script>
		window.location.href="../index.php"
	</script>
</head>
<body>
	<div class="page_title">
		<img src="./image/detector.png" />
		<div class="buttonText2">Room 601</div>
		<div class="buttonText2">Smoke Detector</div>
	</div>
	<button class="button" id="send_alarm" onclick="sendAlarm()">
		<img src="./image/alarm.png" />
		<div class="buttonText1">click here to</div>
		<div class="buttonText2">ALARM!</div>
	</button>
	<div id="table_block">
		<table id="table">
			<tr>
				<td>DATE(DD/MM/YYYY)</td>
				<td>MONITOR DATA</td>
				<td>STATE</td><!--auto generated by monitor data-->
				<td>ROOM</td>
			</tr>
			<?php
				foreach ($alarms as $alarm) {
					echo('
						<tr>
							<td>15/09/2020</td>
							<td>273,444/cc</td>
							<td>Abnormal</td>
							<td>Room 601</td>
						</tr>
					');
				}
			?>
		</table>
	</div>
</body>
</html> 